copy button functionality resolved
arjungarg07/urlshortener pull request #16
Opened 2020-12-04 10:10 UTC by balaji2210

2020-12-07 19:13 UTC, arjungarg07 commented
Have you tested the changes @balaji2210? Can you provide a gif of your changes working correctly and please mention the changes you have made in the description while raising a PR for the maintainer's convenience.Thanks.

2020-12-07 21:47 UTC, balaji2210 commented
![captured](https://user-images.githubusercontent.com/63396862/101409261-ac19f700-3903-11eb-9d87-2f56061bd336.gif)

2020-12-07 22:08 UTC, arjungarg07 commented
Well done.Thanks!

2020-12-07 22:12 UTC, arjungarg07 requested changes

2020-12-07 22:12 UTC, arjungarg07 commented on public/js/index.js
> +	document.getElementById('copy').innerText='Copied'
Remove this change and make a separate PR for it. You shall also change the CSS to a lil bit darker respective to the current color of the btn.

2020-12-07 22:34 UTC, closed without merging

2020-12-08 00:37 UTC, arjungarg07 commented
Are you working on it? @balaji2210

2020-12-08 06:25 UTC, balaji2210 commented
> Are you working on it? @balaji2210

yes  I have made a new PR